import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Don't leak the framework in headers.
  poweredByHeader: false,
  // Next 16: AVIF first, WebP fallback for the smallest payloads (LCP budget).
  images: {
    formats: ["image/avif", "image/webp"],
    // Add CDNs we actually pull from (Sanity image pipeline).
    remotePatterns: [{ protocol: "https", hostname: "cdn.sanity.io" }],
  },
  // Inline the (small, atomic Tailwind) CSS into the HTML <head> as a <style> tag instead
  // of a render-blocking external <link>. Removes the one render-blocking request on first
  // load -> faster FCP/LCP on throttled mobile. Applies in production builds only; Tailwind's
  // atomic CSS stays compact so the inlined HTML does not bloat.
  experimental: {
    inlineCss: true,
  },
  // NOTE (Next 16): caching is opt-in. When we add CMS data we can enable
  // `cacheComponents: true` + `'use cache'`. Marketing pages are statically
  // generated by default, which is exactly what we want — leave it off for now.

  // 1:1 301 map from the OLD live site's indexed URLs to their new-site equivalents,
  // staged for the real-domain cutover (verified against the old sitemap). Pages whose
  // slug is unchanged (/, /careers, /privacy-policy, /blog, and the web-design-development,
  // mobile-app-development and digital-marketing service slugs) need no entry. The legacy
  // blog posts have no direct successor, so each 301s to its most topically-relevant page.
  // Apex->www canonicalization is handled at the hosting layer, not here.
  async redirects() {
    return [
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/terms-of-service", destination: "/terms", permanent: true },
      { source: "/services/website-maintenance", destination: "/services/website-maintenance-services", permanent: true },
      { source: "/services/ui-ux-design-branding", destination: "/services/ui-ux-design-services", permanent: true },
      { source: "/services/custom-business-solutions", destination: "/services/custom-software-development", permanent: true },
      { source: "/blog/the-future-of-web-design-embracing-ai-and-immersive-experiences", destination: "/services/web-design-development", permanent: true },
      { source: "/blog/custom-business-solutions-for-2025-streamline-operations-with-intention-infoservice", destination: "/services/custom-software-development", permanent: true },
      { source: "/blog/top-ui-ux-branding-strategies-for-2025-build-trust-with-intention-infoservice", destination: "/services/ui-ux-design-services", permanent: true },
      { source: "/blog/website-maintenance-best-practices-for-2025-keep-your-site-thriving-with-intention-infoservice", destination: "/services/website-maintenance-services", permanent: true },
      { source: "/blog/why-it-consulting-is-essential-in-2025-scale-smarter-with-intention-infoservice", destination: "/services", permanent: true },
      { source: "/blog/effective-digital-marketing-strategies-for-2025-grow-your-brand-with-intention-infoservice", destination: "/services/digital-marketing", permanent: true },
      { source: "/blog/innovative-mobile-app-development-techniques-for-2025-stay-ahead-with-intention-infoservice", destination: "/services/mobile-app-development", permanent: true },
      { source: "/blog/latest-website-design-trends-2025-elevate-your-online-presence-with-intention-infoservice", destination: "/services/web-design-development", permanent: true },
      { source: "/blog/top-digital-transformation-trends-in-2025-powering-business-growth-with-intention-infoservice", destination: "/services/custom-software-development", permanent: true },
    ];
  },
};

export default nextConfig;
