import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Don't leak the framework in headers.
  poweredByHeader: false,
  // Next 16: AVIF first, WebP fallback for the smallest payloads (LCP budget).
  images: {
    formats: ["image/avif", "image/webp"],
    // Add CDNs we actually pull from (Sanity image pipeline).
    remotePatterns: [{ protocol: "https", hostname: "cdn.sanity.io" }],
  },
  // NOTE (Next 16): caching is opt-in. When we add CMS data we can enable
  // `cacheComponents: true` + `'use cache'`. Marketing pages are statically
  // generated by default, which is exactly what we want — leave it off for now.
};

export default nextConfig;
