import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Reveal } from "@/components/ui/Reveal";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { IconSpark, IconCpu, IconLayout, IconEye, IconPlay, IconLayers, IconCode, IconGauge, IconCheck, IconRocket, IconRefresh, IconServer } from "@/components/icons";

// The E-E-A-T CENTREPIECE and the whole proof substitute - we have shipped zero apps and written
// zero Dart, so the depth of what this page knows about owning every pixel IS the demo. It is also
// the answer the signature needs: "ours to get wrong" only reads as seniority if the hard parts
// are immediately owned as capabilities we engineer.
//
// SIX HARD RULES ENFORCED HERE:
// 1. NO VERSION NUMBERS. Impeller, Dart AOT, Material and Cupertino are named as FEATURES. Flutter
//    and Dart release numbers drift across sources and would date the page instantly.
// 2. NO BENCHMARKS OR SIZES. No fps, no frame times, no "70% fewer dropped frames", no megabytes.
//    Card 1 says "no first-run shader jank", NOT "jank-free rendering" - Impeller precompiles
//    shaders at engine-build time; it does not eliminate layout jank or main-isolate overwork.
// 3. NO ACCESSIBILITY OUTCOME CLAIM. Card 4 claims the METHOD (we author semantics and test on real
//    assistive tech), never the outcome ("accessible", "WCAG 2.1 AA"). Flutter's a11y is genuinely
//    weaker than native HTML, and we have shipped zero Flutter apps. Same scrupulousness that made
//    the UI/UX page soften its "visible focus state" claims.
// 4. NAME THE OS-LOOK GAP, DON'T CLAIM WE CLOSED IT. Card 3: when Apple ships a new design language,
//    Flutter's Cupertino set lags it until the framework catches up. We bridge with native platform
//    views and say where the gap is. Claiming we "close the gap" would assert a shipped capability.
// 5. NO OTA PARITY WITH REACT NATIVE. Flutter compiles ahead of time to native code, so there is no
//    sanctioned JavaScript-style code push. Card 11 states that plainly - never a way around review.
// 6. CAPABILITY TENSE ONLY. "we build", "we author", "we profile" - never "our Flutter apps".
//
// Dart macros are deliberately absent: that effort was stopped in early 2025 and augmentations
// replaced it, so presenting macros as "upcoming" would be a dated-vocabulary tell.
const caps = [
  { icon: <IconSpark className="h-5 w-5" />, t: "Impeller, and no first-run shader jank", d: "Flutter's current rendering engine precompiles a small, fixed set of shaders when the engine is built, so a screen doesn't stutter the first time an effect appears. It doesn't make an app immune to jank, so we still profile motion on real, mid-range devices." },
  { icon: <IconCpu className="h-5 w-5" />, t: "Dart, ahead-of-time compiled", d: "A release build compiles your Dart, and the SDK's, into native machine code for each platform - no JavaScript engine interpreting at runtime. In development it runs on a virtual machine instead, which is what makes stateful hot reload possible." },
  { icon: <IconLayout className="h-5 w-5" />, t: "Platform fidelity, and the gap we name", d: "Material on Android, Cupertino patterns on iOS, adaptive layouts across screen sizes. Because Flutter draws its own widgets, when Apple ships a new design language Flutter's Cupertino set lags it until the framework catches up. Where a screen must match the newest OS look now, we bridge it with native platform views and tell you where the gap is up front." },
  { icon: <IconEye className="h-5 w-5" />, t: "Accessibility semantics, authored by hand", d: "Flutter exposes a semantics tree to VoiceOver and TalkBack. Standard widgets emit it automatically, but anything custom-drawn must be given labels, roles and actions explicitly - so screen-reader support, dynamic text scaling, contrast, focus order and touch targets are build work we do and verify on real assistive tech, not defaults the OS grants." },
  { icon: <IconPlay className="h-5 w-5" />, t: "Motion and gestures, engineered", d: "Implicit and explicit animations, physics-based transitions and gestures that feel like the platform expects. Heavy work moves off the main isolate so the frame budget belongs to the interface, and we profile it on the mid-range hardware your users actually hold." },
  { icon: <IconLayers className="h-5 w-5" />, t: "A state architecture you can inherit", d: "Riverpod or Bloc chosen deliberately and used consistently, not three patterns fighting in one repository. The real cost of Flutter state management is inheriting somebody else's choice, so we document ours and keep it boring enough that the next team can read it." },
  { icon: <IconCode className="h-5 w-5" />, t: "Native interop when Dart runs out", d: "Platform channels with type-safe bindings generated by Pigeon, and Dart FFI straight into C libraries. When a Flutter app needs real Swift or Kotlin - an SDK, a sensor, a legacy system - we write it, rather than working around it with something that breaks at the next OS release." },
  { icon: <IconGauge className="h-5 w-5" />, t: "Download size, engineered and measured", d: "Flutter ships its own engine, so a Flutter app has a size floor a thin native app doesn't, and we won't pretend otherwise. We bring it down the documented ways - tree shaking, split builds per architecture, deferred components, trimmed assets - and measure the real number on your build." },
  { icon: <IconCheck className="h-5 w-5" />, t: "Widget, golden and integration tests", d: "Widget tests for behaviour, golden tests to catch the pixel regressions that matter most when you draw every pixel yourself, and integration tests driven on real devices across the OS versions your audience actually runs." },
  { icon: <IconRocket className="h-5 w-5" />, t: "Build, signing and store release", d: "Reproducible builds, code signing, TestFlight and Play internal testing tracks, and submission to both stores. We build to each store's current review and testing requirements, which we confirm at kickoff, so a launch date is a real date." },
  { icon: <IconRefresh className="h-5 w-5" />, t: "Releases without a code-push escape hatch", d: "Because Flutter compiles ahead of time, there is no sanctioned JavaScript-style over-the-air code push. Where it helps, Shorebird can patch Dart-level changes inside the store rules - never native code, plugins or assets, and never a way around review. So we keep what can safely change behind remote config and feature flags, and plan the release cadence honestly." },
  { icon: <IconServer className="h-5 w-5" />, t: "Backend, data and offline", d: "Firebase, Supabase or the API you already run, with a local store, an explicit sync strategy and real conflict rules where the app genuinely has to work without a connection - and an honest conversation about which screens actually do." },
];

export function FlutterCapabilities() {
  return (
    <Section>
      <Container>
        <Reveal>
          <SectionHeading
            eyebrow="How we build Flutter"
            title="Twelve things the platform won't do for you"
            sub="This grid is the argument of this page. When a toolkit draws its own pixels, nothing arrives correct by default - not the platform feel, not the accessibility semantics, not the motion, not the size. Each of these is a decision somebody has to make on purpose, and this is how we make them."
          />
        </Reveal>

        <Reveal group className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {caps.map((c) => (
            <div key={c.t} className="card flex flex-col p-5">
              <span aria-hidden="true" className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-border bg-surface-2 text-brand-500">
                {c.icon}
              </span>
              <h3 className="mt-4 font-display text-sm font-semibold text-foreground">{c.t}</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{c.d}</p>
            </div>
          ))}
        </Reveal>

        {/* "Our default FLUTTER build" = the stack we use WHEN FLUTTER IS CHOSEN. It must never
            read as "Flutter is our default" - RnCompare byte-locked that cell to React Native. */}
        <Reveal className="mt-6">
          <div className="rounded-2xl border border-border bg-muted/50 p-6">
            <p className="max-w-3xl text-sm leading-relaxed text-muted-foreground">
              <span className="font-semibold text-foreground">Our default Flutter build:</span> Dart
              with sound null safety and the modern language features - records, patterns, sealed
              classes - on Flutter&apos;s current rendering engine. One state-management choice, made
              deliberately and used consistently, because the expensive part of a Flutter codebase is
              never the widgets, it is the architecture the next team inherits. A design system
              expressed as a themed widget library rather than styling scattered across screens, since
              drawing your own pixels only pays off if the drawing is centralised. Platform fidelity
              treated as work: Cupertino patterns on iOS, Material on Android, and native platform
              views wherever the framework has not yet caught up with a new OS look. Accessibility
              semantics authored from the first screen and verified on real assistive technology,
              because nothing is inherited from the operating system. Heavy work off the main isolate,
              motion profiled on mid-range hardware, size trimmed the documented ways and measured on
              your build rather than promised as a number. Native code written by hand through
              platform channels or Dart FFI when the ecosystem stops. And we plan the release cadence
              around the fact that a real code change ships through store review rather than around
              it. Where we would not reach for Flutter is when your team already lives in React, when
              the product genuinely needs native from day one, or when the thing you are building has
              to be found by a search engine.
            </p>
          </div>
        </Reveal>
      </Container>
    </Section>
  );
}
